### ISSUE TITLE
OmniSharp Org meeting?

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/OmniSharp#1]
Seems like it's a good time to have another meeting, it's been many months since we had the last one!

Agenda items?
- OmniSharp using `csi`
- scaffolding?
- generators?
- vscode plugin?
- Make a recurring meeting?
  - perhaps once a month?
  - How do we best handle various time zones of all the individuals involved?

cc @OmniSharp/owners  @OmniSharp/generator-aspnet-team-push @OmniSharp/scaffolding-admins @OmniSharp/omnisharp-vim @OmniSharp/gen-csharp-dev

**Comment by peterblazejewicz** [comment]
> How do we best handle various time zones of all the individuals involved?

Publish agenda before as issue with e.g. todo checklists, so people could make statements before meeting in proper place (e.g. gists or online docs). For example I do really have a short time window to get involved in any online discussion properly - excepts of weekends.
https://github.com/blog/1825-task-lists-in-all-markdown-documents
IO.js routines: https://github.com/nodejs/node/issues/112 https://github.com/nodejs/node/issues/211
Reuse [Gitter OmniSharp channel](https://gitter.im/OmniSharp)
Thanks!

**Comment by sayedihashimi** [comment]
I think that meeting would be great. I'm on vacation until 12/1, can we do it after that? If not I can catch the next one. For time zones its best effort. If it's recurring we can find two slots and alternate.

**Comment by dmccaffery** [comment]
I am on the west coast with most of MS, so I should be fairly easy to work with -- also, I rarely sleep, so any time is mostly good for me.

**Comment by mikavilpas** [comment]
What time was it last time? I think I'm the furthest away from the rest of
you guys, and the time was okay for me for the last meeting.

2015-11-21 22:44 GMT+02:00 Deavon M. McCaffery notifications@github.com:

**Comment by mikavilpas** [comment]
Sorry, left out the perhaps non-obvious fact that I'm UTC+2 here in Finland
right now. :)

2015-11-22 8:20 GMT+02:00 Mika Vilpas mika.vilpas@gmail.com:

**Comment by DustinCampbell** [comment]
Count me in!

**Comment by shmuelie** [comment]
I'm in, EST here

**Comment by sayedihashimi** [comment]
The last meeting was at 11 AM PT.

**Comment by jrieken** [comment]
+1

**Comment by david-driscoll** [comment]
Sorry, I've been kind of busy the last week or so.

@peterblazejewicz I'll see if I can start working on an agenda in the next day or so.  I agree that we should have some form of notes, and history of what we've said / done.

**Comment by david-driscoll** [comment]
I'm EST, but have no problem with early morning / late evening / weekends.

So we have UTC-8 (PST), UTC-5 (EST), UTC+1 (Poland), UTC+2 (Finland), I've also added Sydney to the list, because I know we have some Aussies as well, not sure if they are looking to participate or not (please do chime in if you want to!).

That leaves us a window of approximately 8 hours if we were to have a phone conversation as well as note taking.  I would prefer to include everyone we possibly can, which is why I even added in the night times for those of us in North America (I know the EST ones are rough, but I'm willing to try and do what I can).

Let me know if I'm missing something with this list.

| PST (UTC-8) | EST (UTC-5) | UTC | UTC+1 | UTC+2 | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 08:00 am | 11:00 am | 16:00 | 17:00 | 18:00 | 03:00 |
| 09:00 am | 12:00 pm | 17:00 | 18:00 | 19:00 | 04:00 |
| 10:00 am | 01:00 pm | 18:00 | 19:00 | 20:00 | 05:00 |
| 11:00 am | 02:00 pm | 19:00 | 20:00 | 21:00 | 06:00 |
| 12:00 pm | 03:00 pm | 20:00 | 21:00 | 22:00 | 07:00 |
| 01:00 pm | 04:00 pm | 21:00 | 22:00 | 23:00 | 08:00 |
| 10:00 pm | 01:00 am | 06:00 | 07:00 | 08:00 | 17:00 |
| 11:00 pm | 02:00 am | 07:00 | 08:00 | 09:00 | 18:00 |

**Comment by Mpdreamz** [comment]
Sign me up too, UTC+1

**Comment by DustinCampbell** [comment]
I can't speak for @davidfowl (who works insane hours) but I'm always in around 07:00 PST (UTC-8).

**Comment by sayedihashimi** [comment]
If we want @davidfowl to join it will need to be after 10:30 AM PT.

**Comment by dmccaffery** [comment]
Someone needs to build an app where everyone selects the time(s) that work for them, and the one with the most votes wins... :8ball:

**Comment by dmccaffery** [comment]
We could use a google hangout, or similar, to record the meeting for others to watch later if they can't make it as well. Like the ASP.NET Community Standup -- just a thought... Not sure if anyone wants to see my ugly face, or all of the cans of red bull stacked on my desk. :sob:

**Comment by sayedihashimi** [comment]
If someone else runs the hangout that's fine, I haven't gotten it to work for me.

**Comment by david-driscoll** [comment]
I'd be happy to host the hangout, just have to figure out how it works first.  I'm going to make some agenda items tonight, and pick 2 times from the list above and we can just vote on those.

This week is thanksgiving for these crazy Americans (everyone knows thanksgiving is in October, _he says as he's living in the states_).  I figure we can target sometime next week?

@peterblazejewicz mentioned weekends might be better, does anyone else have a preferred day that works out for their schedule better?

**Comment by david-driscoll** [comment]
`Availability:` Any day of the week
`Preferred Time:` Anytime
`Preferred Day:` Wednesday

**Comment by DustinCampbell** [comment]
Next week works for me. I'll do my best to clear my schedule for whatever slot we pick.

**Comment by shmuelie** [comment]
Next week works better for me too

**Comment by willl** [comment]
I'm in UTC +11 (Melbourne). 

Based on initial discussions in the #omnisharp channel on [jabbr](https://jabbr.net/#/rooms/omnisharp), would something around 21:00-22:00 UTC work?

**Comment by ctolkien** [comment]
Also in UTC+11 and agree with ~21:00. Would put it early morning for Australia, Late-ish, but still reasonable for UK, and middle of the day for USA people?

**Comment by david-driscoll** [comment]
That starts to kick out the times for @peterblazejewicz, @sp3ctum, @Mpdreamz, @jrieken, etc

Would these times work for everyone?

| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+1) | Helsinki (UTC+2) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 1:00 PM | 4:00 PM | 9:00 PM | 10:00 PM | 11:00 PM | 8:00 AM |

**Comment by spboyer** [comment]
:+1:

**Comment by DustinCampbell** [comment]
:+1:

Now we just need a day.

**Comment by shmuelie** [comment]
Works for me

**Comment by david-driscoll** [comment]
For day I was thinking Wednesday December 2nd @ 21:00 UTC

That's just my selfish choice, I'm open other days as well. :smile:

**Comment by ctolkien** [comment]
And of course... I  can do any day, but Dec 2 :crying_cat_face: 
Edit:
Disregard that... I don't understand timezones.. that's Dec3 for me.. all good :)

**Comment by david-driscoll** [comment]
well for you it would be December 3rd wouldn't it?

**Comment by DustinCampbell** [comment]
Wednesday works for me. Normally that's the C# language design meeting, but I think we're on hiatus for a bit while @MadsTorgersen is out of town. I'll also be bringing @MattWar and @CyrusNajmabadi along as well if that's OK. We'd love to get on the agenda to talk about the C# team's ambitions (and why @MattWar has been prototyping stuff over on his Roslyn fork).

**Comment by willl** [comment]
:+1: For Thursday, December 3rd at 8am AEST (UTC+11)

**Comment by david-driscoll** [comment]
I've added the first draft of the agenda in #2, time is currently tentative pending feedback from everyone else.

**Comment by mikavilpas** [comment]
Either the 2nd or 3rd December at 2300 UTC+2 will work for me. Though I'd
prefer an hour earlier if it's all right with people. I realize setting a
time is pretty difficult since people are spread so widely around the globe
:)

2015-11-25 5:45 GMT+02:00 David Driscoll notifications@github.com:

**Comment by Yantrio** [comment]
I can make Dec 2nd at 9pm utc, doubt I will have much to say but I can chime in a bit about brackets if @mat-mcloughlin can't make it.

**Comment by david-driscoll** [comment]
I have marked #2 as no longer tentative, if anyone has any more questions, or feels we need to meet a different day or time, let us know asap!

**Comment by david-driscoll** [comment]
Apparently the original issue didn't cc everyone, so I've added a new cc list.

FYI incase you haven't seen this issue cc @OmniSharp/all

**Comment by filipw** [comment]
gonna be there!

**Comment by jrieken** [comment]
+1

**Comment by peterblazejewicz** [comment]
:+1:
