### ISSUE TITLE
VIM Omnisharp-roslyn integration fails when server starts automatically

### ISSUE THREAD

**Issue by martin-sweeney** [OmniSharp/OmniSharp#10]
When using roslyn and vim together in omnisharp the following message is shown whenever the server is started. I am using the automatic starting of the server as decribed in the installation notes on github.

/var/folders/39/w91g26n56ld31s3spxy1cwg00000gn/T/vHyf7fm/5:48: no such file or directory: /Users/jtbmanagementserviceslts/.vim/bundle/omnisharp-vim/omnisharp-roslyn/scripts/Omnisharp
--- Press ENTER to continue ---

[Steps]
- Download from github (using pathogen method)
- install vim-dispatch
- install syntastic
- install youcompleteme
- install ctrl.p
- cd ~/.vim/bundle/omnisharp-vim/omnisharp-roslyn
- run  ./build.sh
- download yeoman / yeoman aspnet generator
- run yo aspnet 
- choose 'web application'
- run  dnu restore
- run  dnu build (2242 errors here - if you use coreclr / mono compiles)
- run dnx web
- vim startup.cs - to load a c# file and vim roslyn fails in background
# Additional information:

 ./install.sh fails when you run from scripts directory in omnisharp-roslyn
# 
# python

$python -h
usage: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python [option]
# 
# My .vimrc

"let g:OmniSharp_server_type='v1'
let g:OmniSharp_server_type = 'roslyn'
" If you are using the omnisharp-roslyn backend, use the following
let g:syntastic_cs_checkers = ['code_checker']
# 
# dnvm settings 

$dnvm list
Active              Version Runtime Architecture OperatingSystem Alias

---

```
            1.0.0-beta4    mono                    linux/osx
      1.0.0-rc1-update1 coreclr          x64          darwin default
      1.0.0-rc1-update1    mono                    linux/osx
      1.0.0-rc1-update1 coreclr          x64          darwin default
      1.0.0-rc1-update1 coreclr          x64           linux
      1.0.0-rc1-update1    mono                    linux/osx
        1.0.0-rc2-16595 coreclr          x64          darwin
        1.0.0-rc2-16595    mono                    linux/osx
 *      1.0.0-rc2-20221 coreclr          x64          darwin
        1.0.0-rc2-20221    mono                    linux/osx
```

**Comment by DustinCampbell** [comment]
This issue was moved to OmniSharp/omnisharp-vim#285

**Comment by DustinCampbell** [comment]
This issue was moved to OmniSharp/omnisharp-vim#286
