### ISSUE TITLE
OmniSharp Agenda » Meeting Tuesday March 22th @ 20:30 UTC

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/OmniSharp#11]
## Recording

You can view the meeting at https://youtu.be/wmGsYBUupjY
## Time

| PST (UTC-7) | EST (UTC-4) | London (UTC) | Zürich (UTC+1) | Helsinki (UTC+2) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 1:30 PM | 4:30 PM | 8:30 PM | 9:30 PM | 10:30 PM | 7:30 AM |

NOTE: I realize this is very short notice, this is entirely my fault, I'll make sure to get the next one with at least a weeks notice for April!!!
## Meeting info

[Join skype meeting](https://meet.lync.com/microsoft/sayedha/ZP85BD81)

Join by Phone
Toll-free number: +1 (866) 641-7188 or Toll number: +1 (773) 917-4061 
[Find a local number](https://dialin.lync.com/microsoft.com/sayedha)

Conference ID: 280856 

[Help](https://support.office.com/en-us/article/Skype-for-Business-meeting-help-e0bc00a0-b01f-4f51-88fa-6f74abefa203?ui=en-US&rs=en-US&ad=US)
## Agenda

If you can think of any more agenda items, feel free to edit the issue (if you have permissions) or just comment on this thread and we'll make sure to group them up before the meeting.

Also feel free to discuss any agenda items early as part of this issue, we can make sure to recap during the start of the meeting, and may cut down on the time we have to spend on some of them.
### Project Management

There's a lot of stale issues and backlog items. Let's chat about how we get clean and stay clean.
### Telemetry

No updates yet, see #5 for details.
### C# Team's Ambitions for OmniSharp  <sub>via @dustincampbell</sub>

Assuming no new updates here, but we'll keep it as a talking point. :smile: 
### `dotnet` cli

**dotnet cli** has been **_merged_** to both `master` (pinned) and of course `dev`.  Moving forward we want to keep dev as stable as possible.
### OmniSharp-atom
- Removed most react dependencies, might be a few remaining.
- Focusing on making it easier to work with atom text editor instances.
- Migration has started for `rxjs5.beta3`!
### OmniSharp-node-client
- Added the ability to download the runtime, worked through a few hiccups there.
  - Now the node client downloads an appropriate runtime for the user
  - Currently defaults to mono
  - If they are on mac/linux, and do not have mono, we fall back to coreclr.
  - The end game is to have this configurable, and move to CoreClr as the default eventually.
- With v4 migrated to `rxjs5.beta3`
### OmniSharp-vscode
- Landed! https://github.com/OmniSharp/omnisharp-vscode
- Updates? Progress? Goals?
- Contributors outside Microsoft?
  - plumbing is currently in progress to accept cla contributions
### OmniSharp-roslyn
- We've now moved to cli, off of dnx.
- What else?
### OmniSharp-scaffolding
- _Any information / updates?_
### OmniSharp-brackets
- _Any information / updates?_
### OmniSharp-sublime
- _Any information / updates?_
### OmniSharp-emacs
- _Any information / updates?_
  cc @ianbattersby
### Additional agenda items?

Either update the issue, or add them in the comments below!

cc @OmniSharp/all

**Comment by filipw** [comment]
22 March is Tuesday :)

**Comment by filipw** [comment]
I would also like to point out that USA and Canada are on DST right now but Europe isn't yet, so what was 6h time difference to Zurich is today just 5h time difference :smile:

**Comment by david-driscoll** [comment]
I am just full of win today.

@OmniSharp/all times updated, and the title updated it is supposed to be today (Tuesday)

**Comment by codewithtyler** [comment]
Can someone please record today's meeting?

**Comment by dmccaffery** [comment]
I am so looking forward to this; missed the last two.

**Comment by david-driscoll** [comment]
dotnet waffle!!! https://youtu.be/6dBm1_SI8jE

**Comment by Mpdreamz** [comment]
@sayedihashimi dotnet-waffle looks great at first glance :+1: I love that you can add github sources. 

Random notes during watching:
- it'd be nice if the `cwd` or `git root` are auto included as sources so projects can ship local templates in checkouts without poluting the overal available templates.
- support org_or_user/repository syntax for github repositories
- Another good thing to have from the get go are namespaces, so a full template id is namespace@template in case of template name clashes. You would only need to specify the namespace in case of ambiguity (the org/repos could be default namespace for github sources and local@ for `cwd` `git root` sources)

Noticed small typo spotted in the video `PathReplacemets`, which brings me to a super small nag to use `camelCase` for keywords in the templating language over `PascalCase`

**Comment by dmccaffery** [comment]
Also like the idea of camel case, local templates, and namespaces; watching the video now; yay!

**Comment by sayedihashimi** [comment]
@Mpdreamz 

> - it'd be nice if the `cwd` or `git root` are auto included as sources so projects can ship local templates in checkouts without poluting the overal available templates.

Good idea, issue created https://github.com/sayedihashimi/dotnet-waffle/issues/1.

> - support org_or_user/repository syntax for github repositories

What do you mean? Is there not an https url for that which can be used?

> - Another good thing to have from the get go are namespaces, so a full template id is namespace@template in case of template name clashes. You would only need to specify the namespace in case of ambiguity (the org/repos could be default namespace for github sources and local@ for `cwd` `git root` sources)

I was thinking to add support for a list of **aliases**. So for the template name/id you put the full name and then short names in aliases. When you search, look for name matches first and then if not found look for alias match.

> Noticed small typo spotted in the video PathReplacemets, which brings me to a super small nag to use camelCase for keywords in the templating language over PascalCase

Thanks, issues opened.
https://github.com/sayedihashimi/dotnet-waffle/issues/3
https://github.com/sayedihashimi/dotnet-waffle/issues/2

**Comment by sayedihashimi** [comment]
FYI I have added the video link to the issue text https://youtu.be/wmGsYBUupjY

**Comment by jchannon** [comment]
What's the plan with dotnet new? Are MS shipping with only MVC / WebAPI
templates? With dotnet waffle and yeoman are they going to use any of them?

**Comment by dmccaffery** [comment]
As of right now; dotnet new is 'bare bones' with no intent to support template sources or anything extravagant, which is what is driving the need to create something like this in the first place. That, and the new project dialog is a hunk of crap (no offense, Sayed). :)

**Comment by jchannon** [comment]
I've raised this FYI https://github.com/dotnet/cli/issues/2000

**Comment by spboyer** [comment]
Sorry for the late chime in. But ran across this over the last couple days. Appears this maybe where the `dotnet new` Is headed for templates. TemplTes will be nuget packages and then you will be able to `dotnet new -t <package>`

https://github.com/DamianEdwards/dotnet-new2

@sayedihashimi @jchannon

**Comment by sayedihashimi** [comment]
I've been discussing with @damianedwards for the past few days. Here is where we are at.

For RC2 we're laser focused on investing in the core components and getting the release out the door. For `dotnet new` we are going to enable an experience where users can create projects from the command line. It will be pretty basic, but enough to get past go. Templates will be contained in NuGet packages like what's shown in Damian's video. I'm not sure about the exact templates that will be available on day 1 but it should include templates that are already available in `dotnet new` plus some web template(s). For the web templates I think we'll enable 1 or 2, but I'm not really sure yet.

Since it will be based on NuGet packages it should be possible for you to create templates that can be used by `dotnet new`. In future versions you may need to update your package to get templates to work.

For the more long term we are looking to create something that's more feature rich and that can meet the needs of being plugged into:
- Visual Studio
- Yeoman
- Whatever is next

Some of the ideas that you see in my dotnet-waffle project will make it's way into dotnet-new. The long term hope is that we can author templates in one spot and then plug them into the right experiences. I think we can use this time to work together on dotnet-waffle to flesh out our ideas and how we want the experience to be, so that we can feed that into the RTM/RTM+ version of `dotnet new`

**Comment by dmccaffery** [comment]
So; here's a thought... what if dotnet-new supported the ability to specify within the template.json (or whatever the entry point of the template is) another cli tool to execute... so you could do something like...

template.json:

``` json
{
    "tooling": {
        "cli": "dotnet-waffle",
        "src": "http://nuget.org/packages/dotnet.waffle.nupkg",
        "args": "-dowhatever we want"
    }
}
```

Probably opens up some security vulnerabilities; but as long as we allow the user to opt-in the first time they use a template that calls an external tool with a message like:

"This template wishes to execute a third-party tool (dotnet-waffle) from http://nuget.org/packages/dotnet.waffle.nupkg. Do you want to allow this? y/n?"

I think that avoids any repercussions. Anyway, the main point of this is, we can enable dotnet-new to execute any pipeline, including dotnet-waffle, yo, mustache, or any other templating engine out there through a common CLI interface -- making it immensely flexible in the future without requiring any modifications to dotnet-new itself to support them.

Thoughts?

**Comment by jchannon** [comment]
I think the idea that you can add templates etc is great.

My only question is what MS will ship as a default set of templates?
Ideally I'd like them to ship a Nancy template but in all honestly I expect
hell will freeze over before that happens (maybe that's a little too
strong).

The issue comes down to what 90% of devs are going to do, I imagine most
will just use the templates that are provided OOTB however, imagine if none
were shipped and that then changed the behaviour of the 90% so they have to
go and find them and so all template authors are at an equal standing so to
speak.

Thoughts?

**Comment by jchannon** [comment]
Also I guess we should move this discussion to dotnet.waffle repo..

**Comment by sayedihashimi** [comment]
@dmccaffery I have some thoughts. Give me a few days to write something up and I'll share it.

> Also I guess we should move this discussion to dotnet.waffle repo..

The dotnet-waffle repo is in a temporary location and likely to move at some point, so issues there will be lost at some point. Instead I have created a new issue at https://github.com/aspnet/Templates/issues/464 where we can share thoughts on the command line experience for asp.net projects.

FYI for RC2 it looks like dotnet-new will not significantly change. We have other more critical items that we are going to be focusing on. We will revisit that after RC2 of course and have something for the next release.

**Comment by dmccaffery** [comment]
@sayedihashimi Sounds like a tasty read... looking forward to it. :+1:

**Comment by sayedihashimi** [comment]
I have shared my thoughts at https://github.com/dotnet/cli/issues/2052#issuecomment-207031714
