### ISSUE TITLE
OmniSharp Agenda » Meeting Monday May 16th @ 18:00 UTC

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/OmniSharp#12]
## Time

| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+2) | Helsinki (UTC+3) | Sydney (UTC+10) |
| --- | --- | --- | --- | --- | --- |
| 11:00 AM | 2:00 PM | 6:00 PM | 8:00 PM | 9:00 PM | 4:00 AM |
## Meeting info

[Join skype meeting](https://meet.lync.com/microsoft/sayedha/ZP85BD81)

Join by Phone
Toll-free number: +1 (866) 641-7188 or Toll number: +1 (773) 917-4061 
[Find a local number](https://dialin.lync.com/microsoft.com/sayedha)

Conference ID: 280856 

[Help](https://support.office.com/en-us/article/Skype-for-Business-meeting-help-e0bc00a0-b01f-4f51-88fa-6f74abefa203?ui=en-US&rs=en-US&ad=US)
## Agenda

If you can think of any more agenda items, feel free to edit the issue (if you have permissions) or just comment on this thread and we'll make sure to group them up before the meeting.

Also feel free to discuss any agenda items early as part of this issue, we can make sure to recap during the start of the meeting, and may cut down on the time we have to spend on some of them.
### Project Management

I've been looking at Huboard, as it has the easiest integration with Github today.
### Telemetry

No updates yet, see #5 for details.
### New Project System

It's safe to assume the new [Roslyn Project System](https://github.com/dotnet/roslyn-project-system) will be an important project for us in the near future.  I'd love to know more about what the system is trying to do specifically, and how that relates to OmniSharp.
### OmniSharp-atom
- Trying to keep things maintained, haven't had much time the last 2 months since I'm effectively working 2 jobs at the moment.
### OmniSharp-node-client
- Trying to keep things maintained, haven't had much time the last 2 months since I'm effectively 
- I refactored things a bit, as the notion of multiple client versions didn't make much sense.  We only version API's if there is something newer or better.  So there is one "Reactive" API now, which leaves us open to create an Async API with is promise based.
### OmniSharp-vscode
- Landed! https://github.com/OmniSharp/omnisharp-vscode
- Updates? Progress? Goals?
- Contributors outside Microsoft?
  - plumbing is currently in progress to accept cla contributions
- Use OmniSharp-node-client?
  - On the table as something to do in the future.
### OmniSharp-roslyn
- We've now moved to cli, off of dnx.
- What else?
### OmniSharp-scaffolding
- _Any information / updates?_
### OmniSharp-brackets
- _Any information / updates?_
### OmniSharp-sublime
- _Any information / updates?_
### OmniSharp-emacs
- _Any information / updates?_
  cc @ianbattersby
### Additional agenda items?

Either update the issue, or add them in the comments below!

cc @OmniSharp/all @damianedwards

**Comment by david-driscoll** [comment]
If next week works better, we can always move it.

**Comment by david-driscoll** [comment]
I have one conflict with @sayedihashimi for Friday.  Currently thinking of moving to Monday May 16th at the following time:

| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+2) | Helsinki (UTC+3) | Sydney (UTC+10) |
| --- | --- | --- | --- | --- | --- |
| 11:00 AM | 2:00 PM | 6:00 PM | 8:00 PM | 9:00 PM | 4:00 AM |

Going to wait until tomorrow to make the final decision, let me know if that time is bad for anyone else.

**Comment by peterblazejewicz** [comment]
Folks,

Can it be an hour later? (speaking in UTC+2: 8:00 PM/Warsaw/Poland))

Thanks!

> On 11 May 2016, at 21:02, David Driscoll notifications@github.com wrote:
> 
> I have one conflict with @sayedihashimi https://github.com/sayedihashimi for Friday. Currently thinking of moving to Monday May 16th at the following time:
> 
> PST (UTC-8)   EST (UTC-5) London (UTC)    Zürich (UTC+2) Helsinki (UTC+3)    Sydney (UTC+10)
> 10:00 AM  1:00 PM 5:00 PM 7:00 PM 8:00 PM 3:00 AM
> Going to wait until tomorrow to make the final decision, let me know if that time is bad for anyone else.
> 
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly or view it on GitHub https://github.com/OmniSharp/OmniSharp/issues/12#issuecomment-218557301

Piotr Grzegorz Błażejewicz
e: peter.blazejewicz@gmail.com
m: +48 788 296 547

**Comment by david-driscoll** [comment]
I've updated the times for the moment to shift it that hour.  I'm going to check with @sayedihashimi to make sure that works for him. 

| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+2) | Helsinki (UTC+3) | Sydney (UTC+10) |
| --- | --- | --- | --- | --- | --- |
| 11:00 AM | 2:00 PM | 6:00 PM | 8:00 PM | 9:00 PM | 4:00 AM |

**Comment by peterblazejewicz** [comment]
Super! Appr.

> On 11 May 2016, at 21:09, David Driscoll notifications@github.com wrote:
> 
> I've updated the times for the moment to shift it that hour. I'm going to check with @sayedihashimi https://github.com/sayedihashimi to make sure that works for him.
> 
> PST (UTC-8)   EST (UTC-5) London (UTC)    Zürich (UTC+2) Helsinki (UTC+3)    Sydney (UTC+10)
> 11:00 AM  2:00 PM 6:00 PM 8:00 PM 9:00 PM 4:00 AM
> —
> You are receiving this because you are on a team that was mentioned.
> Reply to this email directly or view it on GitHub https://github.com/OmniSharp/OmniSharp/issues/12#issuecomment-218559362

Piotr Grzegorz Błażejewicz
e: peter.blazejewicz@gmail.com
m: +48 788 296 547

**Comment by david-driscoll** [comment]
Date adjusted to Monday, let me know if there are any other conflicts!

**Comment by DustinCampbell** [comment]
Works for me

**Comment by shmuelie** [comment]
Works for me, and please send a calendar invite :)

**Comment by david-driscoll** [comment]
If I haven't already sent an invite I might not have your email, feel free to email me david.driscoll@gmail.com and I'll add you to the list!

**Comment by DustinCampbell** [comment]
I'd like to add a backlog discussion to the meeting agenda. There are a number of work items we'd like to tackle for our next milestone. Getting everyone on the same page would be awesome!

**Comment by willl** [comment]
Should we fully move all omnisharp related chat to the [omnisharp slack](https://goo.gl/Ovnqr1) rather than jabbr?

Even [David Fowler](https://twitter.com/davidfowl/status/730807211660709888) has joined slack. And jabbr has been struggling with lag and other slowness related issues.

Also, @troydai has added a few "memos" to the [omnisharp-roslyn wiki](https://github.com/OmniSharp/omnisharp-roslyn/wiki), so might be good to mention those?

**Comment by david-driscoll** [comment]
https://github.com/OmniSharp/omnisharp-roslyn/wiki/Memo:-Make-OmniSharp-greater

**Comment by DustinCampbell** [comment]
Potential backlog items:
- C# Editing
  - Better Completion List - Consume new public Completion API from Roslyn
  - Better Signature Help - Consume new public Signature Help API from Roslyn (API in progress)
  - Code Action improvements - Rationalize and fix bugs
  - Performance - Stop passing entire buffer on each character typed
  - Better Syntax Highlighting - Need API from VS Code to allow extension to do more than just provide TextMate grammar
  - Metadata as Source - Create new Roslyn API and update OmniSharp to consume it
- Project Management
  - Startup project for debugging - Add project selector that can modify launch.json
  - Better dotnet restore - Handle dotnet restore better and provide more robust restore commands in VS
  - Project-less experience - Needs design, but the idea is that we should be able to provide basic IntelliSense when no project file exists
  - New file templates - Need to understand what VS Code supports here (if anything)
- New Experiences
  - Razor editing support - Need to investigate
  - Unit testing experience
- OmniSharp improvements
  - Engineering Improvements
  - OmniSharp plug-in system

**Comment by david-driscoll** [comment]
### templates

`dotnet new`
- nuget package based
- plugin into VS, VSCode, yo, etc.

@sayedihashimi has more information if you reach out to him.

**Comment by mikavilpas** [comment]
Hi guys, couldn't make it today but would like to chime in here just to say I'm picking up development with Emacs again after a few months off.

Support for omnisharp-roslyn with a subprocess should be up - all tests passing again! Looking forward to having more time in the summer. :+1:

**Comment by DustinCampbell** [comment]
Awesome @sp3ctum!

**Comment by sayedihashimi** [comment]
Video is at https://youtu.be/IvlOD-KjXRI

**Comment by dmccaffery** [comment]
@sayedihashimi Thanks for recording... I'm sorry I couldn't attend today... I will definitely watch this later, though.
