### ISSUE TITLE
OmniSharp Agenda » Proposed Meeting July 14th @ 18:00 UTC

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/OmniSharp#13]
## Proposed Time

| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+2) | Helsinki (UTC+3) | Sydney (UTC+10) |
| --- | --- | --- | --- | --- | --- |
| 11:00 AM | 2:00 PM | 6:00 PM | 8:00 PM | 9:00 PM | 4:00 AM |
## Meeting info

[Join skype meeting](https://meet.lync.com/microsoft/sayedha/ZP85BD81)

Join by Phone
Toll-free number: +1 (866) 641-7188 or Toll number: +1 (773) 917-4061 
[Find a local number](https://dialin.lync.com/microsoft.com/sayedha)

Conference ID: 280856 

[Help](https://support.office.com/en-us/article/Skype-for-Business-meeting-help-e0bc00a0-b01f-4f51-88fa-6f74abefa203?ui=en-US&rs=en-US&ad=US)
## Agenda

If you can think of any more agenda items, feel free to edit the issue (if you have permissions) or just comment on this thread and we'll make sure to group them up before the meeting.

Also feel free to discuss any agenda items early as part of this issue, we can make sure to recap during the start of the meeting, and may cut down on the time we have to spend on some of them.
### Project Management

I've been looking at Huboard, as it has the easiest integration with Github today.
### Telemetry

No updates yet, see #5 for details.
### Project Che Integration

http://www.eclipse.org/che/
### New Project System

It's safe to assume the new [Roslyn Project System](https://github.com/dotnet/roslyn-project-system) will be an important project for us in the near future.  I'd love to know more about what the system is trying to do specifically, and how that relates to OmniSharp.
### OmniSharp-atom
- Currently working to resolve the outstanding issues.
### OmniSharp-node-client
- I refactored things a bit, there is now less work to support additional endpoints as they are added.  Also made it easier to call native endpoints, (and infact it may become the "standard" way to interact with the server, don't know yet).
### OmniSharp-vscode
- Landed! https://github.com/OmniSharp/omnisharp-vscode
- Updates? Progress? Goals?
- Contributors outside Microsoft?
  - Are now being accepted!
- Use OmniSharp-node-client?
  - On the table as something to do in the future.
### OmniSharp-roslyn
- What else?
### OmniSharp-scaffolding
- _Any information / updates?_
### OmniSharp-brackets
- _Any information / updates?_
### OmniSharp-sublime
- _Any information / updates?_
### OmniSharp-emacs
- _Any information / updates?_
  cc @ianbattersby
### Additional agenda items?

Either update the issue, or add them in the comments below!

cc @OmniSharp/all

**Comment by david-driscoll** [comment]
Moving to July 14th, based on everyones availability this may shift.

**Comment by Yantrio** [comment]
it's worth noting that huboard was already  set up, but not used. https://huboard.com/OmniSharp/omnisharp-roslyn/ may need a cleanup first.

**Comment by dmccaffery** [comment]
Did I miss an update for the July 14 meeting? Is another one on the schedule? :)

**Comment by david-driscoll** [comment]
@dmccaffery there is definitely another one on the schedule, I'd like to have one sometime this month.  @DustinCampbell is on vacation so it'll probably be near the end.

**Comment by DustinCampbell** [comment]
FWIW, I'll be back in the office on Monday, August 15th.
