### ISSUE TITLE
OmniSharp Agenda » Meeting Thursday August 10th, 2017 @ 18:00 UTC

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/OmniSharp#18]
| PST (UTC-8) | EST (UTC-4) | London (UTC+1) | Zürich (UTC+2) | Helsinki (UTC+3) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 11:00 AM | 2:00 PM | 7:00 PM | 8:00 PM | 9:00 PM | 5:00 AM |
## Meeting info

[Join online meeting](https://meet.lync.com/microsoft/dustinca/Z86CEL1T)
https://meet.lync.com/microsoft/dustinca/Z86CEL1T 

Join by Phone 
[+1 (213) 458-7586](tel:+1%20(213)%20458-7586)
[+1 (866) 639-0588](tel:+1%20(866)%20639-0588)
[Find a local number](https://dialin.lync.com/22f12fa0-499f-435b-bc69-b8de580ba330)

Conference ID: 60355518 

[Forgot your dial-in PIN?](https://dialin.lync.com/22f12fa0-499f-435b-bc69-b8de580ba330) | [First online meeting?](http://r.office.microsoft.com/r/rlidOC10?clid=1033&p1=4&p2=1041&pc=oc&ver=4&subver=0&bld=7185&bldver=0)

## Agenda

If you can think of any more agenda items, feel free to edit the issue (if you have permissions) or just comment on this thread and we'll make sure to group them up before the meeting.

Also feel free to discuss any agenda items early as part of this issue, we can make sure to recap during the start of the meeting, and may cut down on the time we have to spend on some of them.

### Mono Runtime!
* Quick overview of the mono runtime changes, and what this means for the project going forward

### Cake Integration Discussion
* We need to discuss a little bit about how best do we want to handle Cake, as well as plugins in general.

### Language Server Protocol
* Currently working on moving OmniSharp off of Kestrel, after that LSP will follow.

### OmniSharp-atom
- Trying to find time to sit and solve the issues surrounding this... I have a new computer, so it'll be easier to handle.  Still splitting time between this LSP, and other work obligations.
- Some problems are left unresolved.
- My hope is that this can be upgraded once atom supports a subset of LSP,  @damieng 😉

### OmniSharp-node-client
- Added custom endpoints to accommodate OmniSharp features that the language server protocol doesn't support.
- LSP 3 support soon

### OmniSharp-vscode
- Updates? Progress? Goals?
- Looking at LSP as a possible option in the future

### OmniSharp-vim
- _Any information / updates?_

### OmniSharp-emacs
- _Any information / updates?_

cc @OmniSharp/all

### Additional agenda items?

Either update the issue, or add them in the comments below!

**Comment by DustinCampbell** [comment]
I'd like to discuss the future of project.json support.

**Comment by devlead** [comment]
@david-driscoll @DustinCampbell I get meeting expired
![image](https://user-images.githubusercontent.com/1647294/29184285-f32db72e-7e05-11e7-8d35-370fad682d78.png)

**Comment by DustinCampbell** [comment]
I haven't created a meeting. @david-driscoll, I didn't realize you were going to try and reuse that. It's not a thing that can be used ongoing. Give me a moment.

**Comment by DustinCampbell** [comment]
I just created a new meeting. Try https://meet.lync.com/microsoft/dustinca/0PCGYH6G

**Comment by DustinCampbell** [comment]
Also:

Join by phone

Toll-free number: +1 (866) 639-0588, access code: 26018306 (Dial-in Number)                   English (United States)  
Toll number:         +1 (213) 458-7586, access code: 26018306 (Dial-in Number)                   English (United States)

**Comment by DustinCampbell** [comment]
Or, [find a local number](https://dialin.lync.com/22f12fa0-499f-435b-bc69-b8de580ba330?id=26018306)
