### ISSUE TITLE
OmniSharp Agenda » Meeting Thursday October 5th, 2017 @ 18:00 UTC

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/OmniSharp#19]
| PST (UTC-8) | EST (UTC-4) | London (UTC+1) | Zürich (UTC+2) | Helsinki (UTC+3) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 11:00 AM | 2:00 PM | 7:00 PM | 8:00 PM | 9:00 PM | 5:00 AM |

## Meeting info
Join Skype Meeting ( https://meet.lync.com/microsoft/dustinca/RRJCBN81 )
Trouble Joining? Try Skype Web App ( https://meet.lync.com/microsoft/dustinca/RRJCBN81?sl=3D1 )

Join by phone
Toll-free number: +1 (866) 639-0588, access code: 96135890 (Dial-in Number)                   English (United States)
Toll number:         +1 (213) 458-7586, access code: 96135890 (Dial-in Number)                   English (United States)

Find a local number ( https://dialin.lync.com/22f12fa0-499f-435b-bc69-b8de580ba330?id=3D96135890 )

Conference ID: 96135890 (same as access code above)
Forgot your dial-in PIN? ( https://mysettings.lync.com/pstnconferencing ) | Help ( http://go.microsoft.com/fwlink/?LinkId=3D389737 )

Welcome to Skype for Business Online Meetings. All participants who use the Join by Phone option must dial the full number for call access..

## Agenda

If you can think of any more agenda items, feel free to edit the issue (if you have permissions) or just comment on this thread and we'll make sure to group them up before the meeting.

Also feel free to discuss any agenda items early as part of this issue, we can make sure to recap during the start of the meeting, and may cut down on the time we have to spend on some of them.

### Language Server Protocol
* Off of kestrel (by default)
* Started work on LSP

### OmniSharp-atom
- Will most likely sunset this in favor of [`ide-csharp`](http://blog.atom.io/2017/09/12/announcing-atom-ide.html) cc @damieng

### OmniSharp-node-client
* Once Lsp lands in OmniSharp we may not need to do anything more here.
* Are there any other dependencies on this outside atom / lsp that I'm not aware of?

### OmniSharp-vscode
- Updates? Progress? Goals?
- Looking at LSP as a possible option in the future

### OmniSharp-vim
- _Any information / updates?_

### OmniSharp-emacs
- _Any information / updates?_

cc @OmniSharp/all

### Additional agenda items?

Either update the issue, or add them in the comments below!

**Comment by david-driscoll** [comment]
Added meeting info

**Comment by filipw** [comment]
unfortuantely due to a last minute issue I will need to skip today 😥

**Comment by david-driscoll** [comment]
https://github.com/OmniSharp/csharp-language-server-protocol/blob/master/src/Lsp/LanguageServer.cs
