### ISSUE TITLE
OmniSharp Agenda » Meeting Wednesday December 2nd @ 21:00 UTC

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/OmniSharp#2]
| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+1) | Helsinki (UTC+2) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 1:00 PM | 4:00 PM | 9:00 PM | 10:00 PM | 11:00 PM | 8:00 AM |
## Meeting info

Join Skype Meeting

https://meet.lync.com/pulsebridge/dmccaffery/Q4PQJTTP

Join by phone
Toll-free Number:
Toll Number:12133795770
Check for more phone numbers

Participant Code:7651619
## Agenda

If you can think of any more agenda items, feel free to edit the issue (if you have permissions) or just comment on this thread and we'll make sure to group them up before the meeting.

Also feel free to discuss any agenda items early as part of this issue, we can make sure to recap during the start of the meeting, and may cut down on the time we have to spend on some of them.

**«Tentative»**
Meeting time is currently based on early feed back from #1.
### OmniSharp Meeting
1. Should we have a recurring meeting?
   - What date and time works best going forward?
2. Does this time work for everyone?
   - Are there any proposals for a different time?
   - Alternating times?
### C# Team's Ambitions for OmniSharp  <sub>via @dustincampbell</sub>

> I'll also be bringing @MattWar and @CyrusNajmabadi along as well if that's OK. We'd love to get on the agenda to talk about the C# team's ambitions (and why @MattWar has been prototyping stuff over on his Roslyn fork).
### OmniSharp-code
- Rumor has it that the omnisharp support for vscode is coming over to the OmniSharp Org
- Are there any additional details?
### OmniSharp-roslyn
- @troydai has some exploratory branches for DNX RC2 support and `dotnet` cli support.
  - https://github.com/troydai/omnisharp-roslyn/tree/trdai/rc2
  - https://github.com/troydai/omnisharp-roslyn/tree/trdai/cli
- This is awesome, but I love to hear more about the motivations, and things that it will give us.
- Where are we with those?
- Where are we with the integration of `dnx` and `dotnet` runtimes?
- Is this something that OmniSharp will have to deal with both `dnx` and `dotnet` much like `kre` before?
- How might plugins factor into this?
### OmniSharp-scaffolding
- Is this a future replacement for the existing `generator-aspnet` project?
- What is our planned support `dnx` and `dotnet`?
### OmniSharp-brackets
- Does anyone want to maintain this?
- Is it worth the effort, when you look at usage of brackets vs vscode vs atom
### OmniSharp-sublime
- @jchannon said that sublime needed some love I think?
- Do we have anyone that wants to work on this?
### OmniSharp-emacs
- Seems to have a pretty active
- Does the emacs team need any support?

From @ianbattersby 

> Apologies for the delay, I had mentioned to David and Jonathan in passing I'd been working on some omnisharp-emacs stuff on my own which might be of interest, might not.
> 
> In summary;
> 
> I've been developing a new Spacemacs layer that aims to;
> 
> Move the the process handling over to Prodigy
> Use prodigy to manage multiple server processes (projects)
> Updates to common files (across projects - why not?)
> Introduce Spacemacs short-cut for solution loading via Prodigy
> Encapsulate some common development orientated tasks;
> Interactive integration tests via Prodigy
> Unit tests running via Prodigy
> Other miscellaneous refactoring that is currently in a state of flux
> Picked up the 'incremental-changes' patch that Jason started and seen that through an almost working state, but it has problems, So currently I'm moving to a new solution for creating the diff changes using the emacs built-in undo history, which should sort these problems.
> 
> During all of this I've been learning elisp, so my progress has been slow, but is getting better! Will PR for your consideration when I reach a point of stability and feature completeness.
### OmniSharp-node-client
- If vscode moves OmniSharp it makes sense to share the client between the two, will make development in tandem easier
  - I know I need to manage releases and breaking a changes a little better if that happens ;)
- Has moved to TypeScript using ES6/ES2015 with Babel compiling down to ES5
- I tried to move to the Alpha RxJS5 but there were still a few issues there.
### OmniSharp-atom
- Has moved to TypeScript using ES6/ES2015 with Babel compiling down to ES5
- Same issues with RxJS5 as OmniSharp-client

**Comment by shmuelie** [comment]
I'd like to add getting more people working on generator-csharp. I admit I haven't had the time lately to work on it, but having just me is bad.

**Comment by david-driscoll** [comment]
I have removed tentative from this meeting, so everyone can assume it's going to happen.

If anyone wants a calendar invite, just hit me up on email @ david.driscoll at gmail.com and I'll send one out.

**Comment by david-driscoll** [comment]
cc @OmniSharp/all

**Comment by sayedihashimi** [comment]
What time is that in Seattle? Want to make sure I don't miss it.

**Comment by david-driscoll** [comment]
I've added the times to the top of the issue, and below.

| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+1) | Helsinki (UTC+2) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 1:00 PM | 4:00 PM | 9:00 PM | 10:00 PM | 11:00 PM | 8:00 AM |

**Comment by david-driscoll** [comment]
I have sent a calendar invite out, if anyone else wants one, just get me your email.

We'll try to see if Google Hangouts will work, then we can keep the session recorded (which would be great) other wise we will fall back to something like Skype for Business.

**Comment by david-driscoll** [comment]
Anyone else with agenda items?  @ianbattersby you mentioned on twitter you might have something?

**Comment by Mpdreamz** [comment]
@david-driscoll can you send me an invite too?

**Comment by jchannon** [comment]
And @yantrio

**Comment by ianbattersby** [comment]
Am on a train, should be back by 8.45 with a decent keyboard. Apologies, I'd thought this was last night originally :)

**Comment by david-driscoll** [comment]
Sent to all three... I think next time I'll just make a script to rip everyones emails out all the repos, and then just use that list rofl.

**Comment by jchannon** [comment]
Thays one way to get a Christmas card list

**Comment by ianbattersby** [comment]
Apologies for the delay, I had mentioned to David and Jonathan in passing I'd been working on some omnisharp-emacs stuff on my own which might be of interest, might not. 

In summary;
- I've been developing a new Spacemacs layer that aims to;
  - Move the the process handling over to Prodigy
  - Use prodigy to manage multiple server processes (projects)
  - Updates to common files (across projects - why not?)
  - Introduce Spacemacs short-cut for solution loading via Prodigy
  - Encapsulate some common development orientated tasks;
    - Interactive integration tests via Prodigy
    - Unit tests running via Prodigy
  - Other miscellaneous refactoring that is currently in a state of flux
- Picked up the 'incremental-changes' patch that Jason started and seen that through an almost working state, but it has problems, So currently I'm moving to a new solution for creating the diff changes using the emacs built-in undo history, which should sort these problems.

During all of this I've been learning elisp, so my progress has been slow, but is getting better! Will PR for your consideration when I reach a point of stability and feature completeness.

**Comment by david-driscoll** [comment]
FYI doing some reading on Hangouts on Air, there is a hard limit of 10 people... I think we have more than 10 people, lol.

Anyone on the Microsoft side a hookup for Skype for Business?  @sayedihashimi @dustincampbell @davidfowl @shanselman

**Comment by dmccaffery** [comment]
I have Zoom and Skype for Business with unlimited users. We can use that.

**Comment by dmccaffery** [comment]
Join Skype Meeting

https://meet.lync.com/pulsebridge/dmccaffery/Q4PQJTTP

Join by phone
Toll-free Number:
Toll Number:12133795770
Check for more phone numbers

Participant Code:7651619

**Comment by dmccaffery** [comment]
I don't have toll free calling for international callers on my plan, unfortunately, but everyone can use audio through PC, Mac, or mobile.

**Comment by ThatRendle** [comment]
Don't know if invites are still required, but I'd like to attend please.

**Comment by david-driscoll** [comment]
@markrendle no invites required! :smile: 

I've been sending calendar invites just to make peoples lives easier so their phone buzzes at them, lol.

**Comment by Mpdreamz** [comment]
Much appreciated @david-driscoll :clap:

**Comment by sayedihashimi** [comment]
I added the meeting info to the main text in the issue here.

**Comment by shmuelie** [comment]
And of course work schedules a last minute meeting at 4PM EST so I can't attend
