### ISSUE TITLE
OmniSharp Agenda » Meeting Tuesday December 12th, 2017 @ 19:00 UTC

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/OmniSharp#21]
| PST (UTC-8) | EST (UTC-5) | London (UTC+0) | Zürich (UTC+1) | Helsinki (UTC+3) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 11:00 AM | 2:00 PM | 7:00 PM | 8:00 PM | 9:00 PM | 6:00 AM |

## Meeting info
-> [Join Skype Meeting](https://meet.lync.com/microsoft/dustinca/B5KRH9KD)
Trouble Joining? [Try Skype Web App](https://meet.lync.com/microsoft/dustinca/B5KRH9KD?sl=1)

Join by phone
 
Toll-free number: +1 (866) 639-0588, access code: 20728715 (Dial-in Number)                 English (United States)  
Toll number:        +1 (213) 458-7586, access code: 20728715 (Dial-in Number)                 English (United States)  
 
[Find a local number](https://dialin.lync.com/22f12fa0-499f-435b-bc69-b8de580ba330?id=20728715)
 
Conference ID: 20728715 (same as access code above)
[Forgot your dial-in PIN?](https://mysettings.lync.com/pstnconferencing) | [Help](http://go.microsoft.com/fwlink/?LinkId=389737)
 
 
Welcome to Skype for Business Online Meetings. All participants who use the Join by Phone option must dial the full number for call access.

## Agenda

If you can think of any more agenda items, feel free to edit the issue (if you have permissions) or just comment on this thread and we'll make sure to group them up before the meeting.

Also feel free to discuss any agenda items early as part of this issue, we can make sure to recap during the start of the meeting, and may cut down on the time we have to spend on some of them.

### Language Server Protocol
* Off of kestrel (by default)
* Started work on LSP

### OmniSharp-atom
- Will most likely sunset this in favor of [`ide-csharp`](http://blog.atom.io/2017/09/12/announcing-atom-ide.html) cc @damieng

### OmniSharp-node-client
* Once Lsp lands in OmniSharp we may not need to do anything more here.
* Are there any other dependencies on this outside atom / lsp that I'm not aware of?

### OmniSharp-vscode
- Updates? Progress? Goals?
- Looking at LSP as a possible option in the future

### C# scripting
 - *new features added recently:* `#r "nuget: {package}"` (shipped) and `#load "nuget: {package}"` (not yet shipped) to reference assemblies and load scripts directly from Nuget
 - *coming up next:* RSP file support for configuring custom references/namespaces in scripting language services
 - *future*:
   - `#load` and `#r` completion support
   - `#r "nuget: {package}"` and `#load "nuget: {package}"` real-time support (currently they are only discovered at startup) - this may require changes in Roslyn to work best

cc @OmniSharp/all

### Additional agenda items?

Either update the issue, or add them in the comments below!

**Comment by david-driscoll** [comment]
NOTE:  The email you recieved might have said Tuesday, this was incorrect the day is Thursday December 7th, that was a copy and fail on my part.

**Comment by david-driscoll** [comment]
Looks like we will be shifting this to next week, probably tuesday... will update tonight

**Comment by filipw** [comment]
Thanks - it's my fault 😊

**Comment by david-driscoll** [comment]
Title updated, moved to Tuesday December 12th!

**Comment by DustinCampbell** [comment]
@david-driscoll : I forwarded a meeting to you with Skype details.

**Comment by gep13** [comment]
@david-driscoll can I just confirm which one is correct?

![image](https://user-images.githubusercontent.com/1271146/33886311-0ee1469a-df3e-11e7-85b2-3fa71f6d4a4a.png)

Thanks

**Comment by david-driscoll** [comment]
Ugh timezones, sorry, the title should have said 19:00 UTC, sorry!  It's been updated as well.

**Comment by david-driscoll** [comment]
Also added skype for business meeting info.

**Comment by gep13** [comment]
@david-driscoll apologies for not being able to attend last night.  Kids had a different idea 😄
