### ISSUE TITLE
OmniSharp Agenda » Meeting Friday May 4th @ 18:00 UTC

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/OmniSharp#23]
| PST (UTC-7) | EST (UTC-4) | London (UTC+1) | Zürich (UTC+2) | Helsinki (UTC+3) | Sydney (UTC+10) |
| --- | --- | --- | --- | --- | --- |
| 11:00 AM | 2:00 PM | 7:00 PM | 8:00 PM | 9:00 PM | 4:00 AM |

## Meeting info
[Join Skype Meeting](https://meet.lync.com/microsoft/dustinca/LGVC55KG)
Trouble Joining? [Try Skype Web App](https://meet.lync.com/microsoft/dustinca/LGVC55KG?sl=3D1)
Join by phone

Toll-free number: +1 (866) 639-0588, access code: 52075514 (Dial-in Number)                 English (United States)
Toll number:        +1 (213) 458-7586, access code: 52075514 (Dial-in Number)                 English (United States)

[Find a local number](https://dialin.lync.com/22f12fa0-499f-435b-bc69-b8de580ba330?id=3D52075514)

Conference ID: 52075514 (same as access code above)
[Forgot your dial-in PIN?](https://mysettings.lync.com/pstnconferencing) | [Help](http://go.microsoft.com/fwlink/?LinkId=3D389737)

Welcome to Skype for Business Online Meetings. All participants who use the Join by Phone option must dial the full number for call access.

## Agenda
TBD

If you can think of any more agenda items, feel free to edit the issue (if you have permissions) or just comment on this thread and we'll make sure to group them up before the meeting.

Also feel free to discuss any agenda items early as part of this issue, we can make sure to recap during the start of the meeting, and may cut down on the time we have to spend on some of them.

### Razor
* What is it going to take?
* What impediments?
* Who can we team up with to help impediments?
* What tasks can be completed in parallel?

### Language Server Protocol
* WIP, need to fix a few bugs to get more endpoints enabled

### `project.json` support
* Discuss

### OmniSharp-atom
- Will most likely sunset this in favor of [`ide-csharp`](http://blog.atom.io/2017/09/12/announcing-atom-ide.html) cc @damieng

### OmniSharp-node-client
* Once Lsp lands in OmniSharp we may not need to do anything more here.
* Are there any other dependencies on this outside atom / lsp that I'm not aware of?

### OmniSharp-vscode
@DustinCampbell @rchande 

### C# scripting
@filipw
* RSP file support, custom host object support
* next: improved #r nuget

cc @OmniSharp/all

### Additional agenda items?

Either update the issue, or add them in the comments below!

**Comment by rchande** [comment]
cc @TheRealPiotrP @akshita31 @jonsequitur

**Comment by david-driscoll** [comment]
Updated to say May 4th, because I cannot read a calendar.

**Comment by shmuelie** [comment]
Won't be able to make it 🙁

**Comment by davidfowl** [comment]
I haven't been to one of these since the early days but can we talk about performance and reliability. I have some feedback now that I've been using VS code and omnisharp as my main dev tool on OSX 😄

**Comment by shmuelie** [comment]
@davidfowl I fear the only solution for improving perf in VS Code is getting them off electron 😄

**Comment by davidfowl** [comment]
> @davidfowl I fear the only solution for improving perf in VS Code is getting them off electron 😄

VS code performance is actually quite fine (even with electron). I'm talking about the performance and reliability of omnisharp and omnisharp-vscode.

**Comment by david-driscoll** [comment]
Call in info added.

**Comment by david-driscoll** [comment]
Notes from todays meeting

--------------------------

Performance
  * MSBuild side performance
  * Out-of-proc compiling executables
  * Multi-node msbuild crossplat
  * Not compiler servers

MSBuild
  * Shipped MSBuild Workspaces (2.9)

Roslyn
  * Public Quick Info API (2.9)
  * Signature Help API (TBD)
  
Razor
  * Need to Visual Studio Editors
  * Ravi to help with editors
  * Try to figure out PMs to pull into discuss stuggles with getting Razor up and running for our purposes.

Language Server Protocol
  * Need to fix a few outstanding bugs

Publish Nuget Packages
  * Take a look through existing API's
    * Filip: Make them all internal by default?
  * OmniSharp.Abstractions is more like OmniSharp.Core

VSCode
  * Shipping 1.15
  * Use latest with omnisharp / use specific version
  * Debugger / source link / symbol server

C# Scripting / Dotnet Script
  * RSP file support
  * Custom Host Object support
  * Move Omnisharp to net461
  * Nuget references only on first pass
    * Roslyn does not support #r to reference into many metadata instances
    * Pending PR to fix this bug

project.json
  * Disable by default
  * Move to separate repository (as plugin?)
  * Figure out what editors are using project.json?
    * Vim
    * Vscode
    * Emacs
    * Sublime

**Comment by davidfowl** [comment]
Sorry I missed this one, //BUILD got me 😄
