### ISSUE TITLE
OmniSharp Agenda » Meeting Thursday November 15th @ 18:00 UTC

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/OmniSharp#24]
| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+1) | Helsinki (UTC+2) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 11:00 AM | 2:00 PM | 7:00 PM | 8:00 PM | 9:00 PM | 6:00 AM |

## Meeting info
`TBD`

## Agenda
General catch up, to figure out what needs to be worked on next (plus more!)

If you can think of any more agenda items, feel free to edit the issue (if you have permissions) or just comment on this thread and we'll make sure to group them up before the meeting.

Also feel free to discuss any agenda items early as part of this issue, we can make sure to recap during the start of the meeting, and may cut down on the time we have to spend on some of them.

### Razor
* Alpha 1 is out!
@NTaylorMullen @danroth27

### Language Server Protocol
* Latest library is updated
* Need to update OmniSharp roslyn with the latest version

### `project.json` support
* Discuss

### OmniSharp-vscode
@DustinCampbell @rchande 

### C# scripting
@filipw
* RSP file support, custom host object support
* next: improved #r nuget

cc @OmniSharp/all

### Additional agenda items?
* analyzers support PR
* NuGet packages release (plugin support)
   - proposal: should we mark everything as internal and release only the basic API surface only (i.e. `IProjectSystem` and few other absolutely core friends), and go from there?

Either update the issue, or add them in the comments below!

**Comment by david-driscoll** [comment]
Also make sure I have the times correct. (I think I double checked them)

**Comment by david-driscoll** [comment]
I forgot to send out the calendar invite, everyone is still welcome to join!

**Comment by rchande** [comment]
Skype link: 
https://meet.lync.com/microsoft/rchande/4D9N3LT7
Skype web app: 
https://meet.lync.com/microsoft/rchande/4D9N3LT7?sl=1

**Comment by david-driscoll** [comment]
Notes:

Attendees:
* Ravi
* Filip
* Dan  Roth
* Drew
* Taylor
* Kevin P


David's TODO's:
* Automate Release Notes
* Azure Pipelines
* LSP
* NuGet Packages
  * Internalize the api surface
  * (copy roslyn)
* .NET Foundation
* vscode incremental buffer changes


Areas / Issues:
* Workspace events: multi threaded -> single threaded
  * Task Scheduler
* Update to .net472
  * Update embedded mono
  * Ensure the latest mono is installed
* Update to Roslyn beta (when released)
  * Microsoft to look internally to determine if this makes sense.
  * Look at different release pipelines
    * `master`
    * `next` / `stable` / `release`
