### ISSUE TITLE
OmniSharp Meeting & Notes - Wednesday December 2nd @ 21:00 UTC

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/OmniSharp#3]
| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+1) | Helsinki (UTC+2) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 1:00 PM | 4:00 PM | 9:00 PM | 10:00 PM | 11:00 PM | 8:00 AM |
## Meeting info

Join Skype Meeting

https://meet.lync.com/pulsebridge/dmccaffery/Q4PQJTTP

Join by phone
Toll-free Number:
Toll Number:12133795770
Check for more phone numbers

Participant Code:7651619
## Agenda

If you can think of any more agenda items, feel free to edit the issue (if you have permissions) or just comment on this thread and we'll make sure to group them up before the meeting.

Also feel free to discuss any agenda items early as part of this issue, we can make sure to recap during the start of the meeting, and may cut down on the time we have to spend on some of them.

**«Tentative»**
Meeting time is currently based on early feed back from #1.
### OmniSharp Meeting
1. Should we have a recurring meeting?
   - What date and time works best going forward?
2. Does this time work for everyone?
   - Are there any proposals for a different time?
   - Alternating times?
### C# Team's Ambitions for OmniSharp  <sub>via @dustincampbell</sub>

> I'll also be bringing @MattWar and @CyrusNajmabadi along as well if that's OK. We'd love to get on the agenda to talk about the C# team's ambitions (and why @MattWar has been prototyping stuff over on his Roslyn fork).
### OmniSharp-code
- Rumor has it that the omnisharp support for vscode is coming over to the OmniSharp Org
- Are there any additional details?
### OmniSharp-roslyn
- @troydai has some exploratory branches for DNX RC2 support and `dotnet` cli support.
  - https://github.com/troydai/omnisharp-roslyn/tree/trdai/rc2
  - https://github.com/troydai/omnisharp-roslyn/tree/trdai/cli
- This is awesome, but I love to hear more about the motivations, and things that it will give us.
- Where are we with those?
- Where are we with the integration of `dnx` and `dotnet` runtimes?
- Is this something that OmniSharp will have to deal with both `dnx` and `dotnet` much like `kre` before?
- How might plugins factor into this?
### OmniSharp-scaffolding
- Is this a future replacement for the existing `generator-aspnet` project?
- What is our planned support `dnx` and `dotnet`?
### OmniSharp-brackets
- Does anyone want to maintain this?
- Is it worth the effort, when you look at usage of brackets vs vscode vs atom
### OmniSharp-sublime
- @jchannon said that sublime needed some love I think?
- Do we have anyone that wants to work on this?
### OmniSharp-emacs
- Seems to have a pretty active
- Does the emacs team need any support?

From @ianbattersby 

> Apologies for the delay, I had mentioned to David and Jonathan in passing I'd been working on some omnisharp-emacs stuff on my own which might be of interest, might not.
> 
> In summary;
> 
> I've been developing a new Spacemacs layer that aims to;
> 
> Move the the process handling over to Prodigy
> Use prodigy to manage multiple server processes (projects)
> Updates to common files (across projects - why not?)
> Introduce Spacemacs short-cut for solution loading via Prodigy
> Encapsulate some common development orientated tasks;
> Interactive integration tests via Prodigy
> Unit tests running via Prodigy
> Other miscellaneous refactoring that is currently in a state of flux
> Picked up the 'incremental-changes' patch that Jason started and seen that through an almost working state, but it has problems, So currently I'm moving to a new solution for creating the diff changes using the emacs built-in undo history, which should sort these problems.
> 
> During all of this I've been learning elisp, so my progress has been slow, but is getting better! Will PR for your consideration when I reach a point of stability and feature completeness.
### OmniSharp-node-client
- If vscode moves OmniSharp it makes sense to share the client between the two, will make development in tandem easier
  - I know I need to manage releases and breaking a changes a little better if that happens ;)
- Has moved to TypeScript using ES6/ES2015 with Babel compiling down to ES5
- I tried to move to the Alpha RxJS5 but there were still a few issues there.
### OmniSharp-atom
- Has moved to TypeScript using ES6/ES2015 with Babel compiling down to ES5
- Same issues with RxJS5 as OmniSharp-client

**Comment by david-driscoll** [comment]
Going to use this issue for notes/minutes/comments/whatever about today's meeting.

**Comment by luisrudge** [comment]
Lync? Really? :D

**Comment by AndersNS** [comment]
Lync is whyiamleaving.net.

Will this be available in some kind of video form? :) I'd be interested to watch it.

**Comment by mikavilpas** [comment]
Smooth, man. :)

2015-12-02 23:43 GMT+02:00 Anders N. Slinde notifications@github.com:

**Comment by david-driscoll** [comment]
Brief minutes:
- Who's who.
- Alternate meeting times, take that offline into another issue, see #4.

## C# / Roslyn / OmniSharp where is the :heart:?
- Great discussion

> - The Roslyn team is looking at how they can take the code intelligence, currently in Visual Studio, and bring it out of process.
>   - Is OmniSharp the answer to that?
>   - Is the direction of the community inline with the direction of Microsoft?
>   - Microsoft has concerns that if the have a deliverable to meet, could they still meet them while still shipping OmniSharp?
>   - Can Microsoft pick and choose the features (ie plugins) that is opt in.
- The answer was, the community basically wants to have a similar experience to OmniSharp, but in our editor of choice.  And that we would love to use the same tool that Visual Studio itself is using.
- _[David D] My comment was that we shouldn't consider Microsoft as an outsider, but instead as a part of our community, and we're one big team._
  - Discussion at #6

## Dotnet CLI / Dnx
- @troydai has a [branch](https://github.com/troydai/omnisharp-roslyn/tree/trdai/cli) where he has OmniSharp working 100% on the CoreClr
- There was a brief demo of the branch working, with an `omnisharp.exe` (woot!)
  - _That is when Skype for Business was cooperating._ :smile: 
- I definitely think it's valuable to bring this into OmniSharp as a separate branch while we get all the kinks worked out.

## OmniSharp Sublime

Needs a maintainer if anyone is interested, reach out to @jchannon for more information.

## Telemetry
- Super controversial?
- Should we do it, should we not do it?
- _What if I don't want my data going to microsoft?_

The answers were basically:
- **Must** be opt-in, ask the user.
- The data should be open for all, this is open source after all
- The Telemetry isn't Microsoft telemetry, it's OmniSharp's Telemetry.
- Discussion at #5

## Generator Aspnet / OmniSharp Scaffolding
- The hope is that OmniSharp scaffolding will supersede generator aspnet at some point in the future, and give us one common tool to scaffold out a new project but we're going to see how it goes.

## Team communication

Currently I'm using the @OmniSharp/all team to cc anyone about OmniSharp, if you want to be added to the team, drop me a line and I'll make sure you're added into that.  Otherwise you can watch this repo, as we're trying to keep our communication open.
