### ISSUE TITLE
Monthly Meeting?  Date / Time discussion...

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/OmniSharp#4]
Follow up from the meeting #3, about the date and time for the meetings.  Feel free to reply to any of the below topics, and we'll figure it out.

I would like to have a monthly meeting so that we the OmniSharp team (that includes Microsofties too!) can catch up on the last months events, and get information on what is happening in the future.
## Do we alternate times?

We used the following times with #3

| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+1) | Helsinki (UTC+2) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 1:00 PM | 4:00 PM | 9:00 PM | 10:00 PM | 11:00 PM | 8:00 AM |

Are there other times we should look at, somehow inverting so it's later in the evening for the North America folks?
## How do we schedule the meeting?

Do we schedule after each meeting, so set a standard day of the month, like the `1st Wednesday of the month` or something like?

**Comment by david-driscoll** [comment]
cc @OmniSharp/all

**Comment by david-driscoll** [comment]
Also would it be possible to get a regularly scheduled Skype for Business meeting (or something similar?)

@dmccaffery has offered to use his if needed.

**Comment by sayedihashimi** [comment]
That sounds great. We can use my Skype as well if it helps.

**Comment by david-driscoll** [comment]
Here's a good tool for looking at all the timezones we're trying to hit.

http://www.timeanddate.com/worldclock/meetingtime.html?month=1&day=6&year=2016&p1=234&p2=207&p3=136&p4=268&p5=101&p6=240&iv=0

**Comment by david-driscoll** [comment]
The only "good" times I can see are the following. 

| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+1) | Helsinki (UTC+2) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 1:00 PM | 4:00 PM | 9:00 PM | 10:00 PM | 11:00 PM | 8:00 AM |
| 11:00 PM | 2:00 AM | 7:00 AM | 8:00 AM | 9:00 AM | 6:00 PM |

 The alternate time puts it late for any East Coast folks (like myself), and then a little early for the London folks. I'm fine attempting to do that, but I might struggle to stay awake that late at night, lol.   

I realize with the first time we run up against midnight for those in UTC+2, so I'm open to sharing the pain if it will help everyone involved.

**Comment by peterblazejewicz** [comment]
> I realize with the first time we run up against midnight for those in UTC+2, so I'm open to sharing the pain if it will help everyone involved.

Yes, but we are the minority I think. Some guys from States are involved in the same project as I, so that does not impact much the purpose of the meetings.

**Comment by david-driscoll** [comment]
Just trying to off options and gather feedback from everyone, if we can make it better / easier / more approachable I'm open to ideas and suggestions.

**Comment by ctolkien** [comment]
With respect to myself, and am speaking for @willl without him knowing (sorry mate)  - it may not be worthwhile to put Europeans out just for us.

I mentioned in Jabbr, now that the long hanging fruit is sorted (particularly for Atom), that my involvement has dropped off. I'd still like to contribute, but it probably won't be in a meaningful way from a code perspective. I've design and other resources here we can leverage, etc. The bigger discussions about Omnisharp that needs to be discussed on call I'm unlikely to offer much on.

Edit, woops pinged the wrong Willl!

**Comment by willl** [comment]
@ctolkien Will with 3 Ls for my github handle. :)

Yeah, Chad is right on the money. 

Also, accommodating a wide range of timezones are a PITA. So if it makes accommodating more people easier, then just exclude the two of us at this time and we'll turn up if it's at a reasonable hour :)

**Comment by dmccaffery** [comment]
Fish are friends, not food. I'm all for being all inclusive. If you shift the meeting between three windows that are 6 house apart, then everyone should have an opportunity to be present at least once every 3 months, no? It may not work out that way in reality, but the maths are there. :)

What does 7AM PST, 1PM PST, and 8PM PST look like across the globes, for instance?

A Google search (or Bing for you die-hard Microsofties, or DuckDuckGo for the tinfoil hat penguin-lovers) later, and I came up with this:

http://everytimezone.com

**Comment by dmccaffery** [comment]
*hours, not house. Stupid autocorrect. :(

**Comment by david-driscoll** [comment]
How does the following times sound for the next meeting?  Bring it back 2 hours so it's a little earlier in the evening for our European friends.

| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+1) | Helsinki (UTC+2) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 11:00 AM | 2:00 PM | 7:00 PM | 8:00 PM | 9:00 PM | 6:00 AM |

**Comment by david-driscoll** [comment]
As far as meeting time and day, what about Wednesday, January 6th @ 19:00 UTC

| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+1) | Helsinki (UTC+2) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 11:00 AM | 2:00 PM | 7:00 PM | 8:00 PM | 9:00 PM | 6:00 AM |

**Comment by ianbattersby** [comment]
As someone in Europe 9pm works better for me personally (commute home + kids bedtime/etc) but certainly not impossible :)

**Comment by jrieken** [comment]
:+1:

**Comment by Yantrio** [comment]
im quite flexible, 7pm and 9pm are both good for me.

**Comment by peterblazejewicz** [comment]
> As someone in Europe 9pm works better for me personally (commute home + kids bedtime/etc) but certainly not impossible :)

:+1:

**Comment by david-driscoll** [comment]
@peterblazejewicz you're UTC+2 right? So which is better for you generally, 9pm or 11pm local time?

**Comment by peterblazejewicz** [comment]
@david-driscoll 

> you're UTC+2 right? So which is better for you generally, 9pm or 11pm local time?
> Yes UTC+2 with DST, and 9pm (the last time I missed most of the meeting though due to kid)

**Comment by mikavilpas** [comment]
I like the suggestion, it's much better for me in Findand, UTC+2 is 2100
:+1:

2015-12-18 23:43 GMT+02:00 Peter Blazejewicz notifications@github.com:

**Comment by ctolkien** [comment]
Just pinging this thread - are we still on for Jan 6th?

Hope everyone had a good break, etc. :)

**Comment by peterblazejewicz** [comment]
I'm on (no mic, kids)

**Comment by jrieken** [comment]
I have to skip today, tho @DustinCampbell is all up to date

**Comment by DustinCampbell** [comment]
Am I? I've been on vacation for the past couple of weeks and am currently in the Midwest at CodeMash. I don't think I'm up to date.

**Comment by david-driscoll** [comment]
I forgot today was Wednesday... lol

Does the time work for everyone?  If not I'm fine postponing until next week.  Vacation == fun :smile: .

**Comment by DustinCampbell** [comment]
I'd prefer waiting til next week. Need to get caught up.

**Comment by jrieken** [comment]
ok, sorry for the surprise @DustinCampbell. next week would be good for me

**Comment by peterblazejewicz** [comment]
> I'd prefer waiting til next week. Need to get caught up.

That's OK. Let David to reschedule meeting. :+1:

**Comment by david-driscoll** [comment]
Sounds good, I'll get everything setup for January 13th @ 19:00 UTC

| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+1) | Helsinki (UTC+2) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 11:00 AM | 2:00 PM | 7:00 PM | 8:00 PM | 9:00 PM | 6:00 AM |

**Comment by jrieken** [comment]
great. thanks

**Comment by sayedihashimi** [comment]
@david-driscoll can you send meeting invites to the MSFT people? Without it I think we may miss the meeting.

**Comment by shanselman** [comment]
Totally.

On Thu, Jan 7, 2016 at 9:43 AM, Sayed Ibrahim Hashimi <
notifications@github.com> wrote:

> @david-driscoll https://github.com/david-driscoll can you send meeting
> invites to the MSFT people? Without it I think we may miss the meeting.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OmniSharp/OmniSharp/issues/4#issuecomment-169752042.

## 

Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by david-driscoll** [comment]
Invites sent out, if I missing anyone please forward, or let me know and I'll get them added.

Also closing the ticket, we can discuss parts of the next meeting in the agenda #7
