### ISSUE TITLE
OmniSharp Agenda » Meeting Wednesday January 13th @ 19:00 UTC

### ISSUE THREAD

**Issue by david-driscoll** [OmniSharp/OmniSharp#7]
| PST (UTC-8) | EST (UTC-5) | London (UTC) | Zürich (UTC+1) | Helsinki (UTC+2) | Sydney (UTC+11) |
| --- | --- | --- | --- | --- | --- |
| 11:00 AM | 2:00 PM | 7:00 PM | 8:00 PM | 9:00 PM | 6:00 AM |
## Meeting info

[Join skype meeting](https://meet.lync.com/microsoft/sayedha/ZP85BD81)

Join by Phone
Toll-free number: +1 (866) 641-7188 or Toll number: +1 (773) 917-4061 
[Find a local number](https://dialin.lync.com/microsoft.com/sayedha)

Conference ID: 280856 

[Help](https://support.office.com/en-us/article/Skype-for-Business-meeting-help-e0bc00a0-b01f-4f51-88fa-6f74abefa203?ui=en-US&rs=en-US&ad=US)
## Agenda

If you can think of any more agenda items, feel free to edit the issue (if you have permissions) or just comment on this thread and we'll make sure to group them up before the meeting.

Also feel free to discuss any agenda items early as part of this issue, we can make sure to recap during the start of the meeting, and may cut down on the time we have to spend on some of them.
### Mailing List

Is there any value in setting up a mailing list to use for questions, discussions, etc?  Or should we keep it on Github?
### Kestrel

https://github.com/OmniSharp/omnisharp-roslyn/pull/370#issuecomment-169793909
- Internally in Kestrel (I'm assuming anyway) the response object is getting reused before the code that is writing out the response
- This could be an `ID10T` error, but any help understanding the mechanics here would be great.
- I hope to have something more before Wednesday.
### Telemetry

There was some [discussion about adding telemetry](https://github.com/OmniSharp/OmniSharp/issues/5).  Basically it sounds like we're okay to explore telemetry so long as it is specificly something the user has to opt-in, from some setthing or prompt of the editor.  Each editor can decide how they want to handle this, but I think most of them will have a prompt of some sort.  If anyone has any insight into how to best handle the case of PII, or telemitry tools that already obfuscate PII for us, that would be good to know about.
### C# Team's Ambitions for OmniSharp  <sub>via @dustincampbell</sub>

Last time there was a [great discussion about potential ambitions](https://github.com/OmniSharp/OmniSharp/issues/2) that the C# team had for their tooling and how would OmniSharp fit into that.

@dustincampbell is there anything to add to that?  Should we invite the c# team again this round?
### `dotnet` cli

Troy is working on a branch with support. (More below)

@filipw has an update for ScriptCS / CSI support using the branch.

> I have been tinkering with Troy's branch to work off it, in order to facilitate scripting support.
> I think the best approach down the road will be to move the "specialized" scriptcs codes, dealing with scriptcs specific to a plugin. But at the same time, we want to have "native", "built-in" support for basic CSX scripting in omnisharp - since scripting is a first class citizen in Roslyn and C# now.
> So I have been working on separating the two, so that we still have some sort of scripting support out of the box in Omnisharp. Hopefully I will have something to share soon - it's been mostly demoware atm, and Troy's stuff has been volatile with dotnet and so on.
### OmniSharp-atom
- Nothing big has happened, I've been focusing on keeping things stable
- Exploring RxJS5 for improved performance
- Also exploring removing React in favor of something else or just manual HTML to avoid some React pitfalls.
### OmniSharp-node-client
- Exploring RxJS5 for improved performance
- Peliminary plugin support exists, though it isn't fully wired up yet.
### OmniSharp-code
- Roslyn team is taking ownership of the OmniSharp plugin for vscode
- There was discussion this would land under the OmniSharp github org.
  - Where are we at with this, still happening?
### OmniSharp-roslyn
- @troydai got a branch that now successfully builds, and appears to produce the correct artifacts for deployment.
  - I found an issue that appears to be Kestrel related, this might be a blocker.
- @troydai is currently working on another branch with a dotnet related release.  
- Is there any other news?  We hit the holiday slow down with the rc2 branch, hopefully we can speed up for the next part of January.
### OmniSharp-scaffolding
- _Any information / updates?_
### OmniSharp-brackets
- _Any information / updates?_
### OmniSharp-sublime
- @jchannon said that sublime needed some love I think?
- Do we have anyone that wants to work on this?
- _Any other information / updates?_
### OmniSharp-emacs
- Seems to have a pretty active
- Does the emacs team need any support?
- _Any other information / updates?_
  cc @ianbattersby
### Additional agenda items?

Either update the issue, or add them in the comments below!

cc @OmniSharp/all

**Comment by david-driscoll** [comment]
I've sent out a meeting invite, if you didn't get one and want one let me know.  If you did get one, and _don't_ want it again, also let me know :smile:.

**Comment by sayedihashimi** [comment]
I have added the skype meeting info to the issue.

**Comment by dmccaffery** [comment]
And I have been booked non-stop for my day job these past few weeks and haven't touched scaffolding. I'm a terrible human being and should be shunned for at least a week. I'll try to make some progress before Wednesday, though.

**Comment by ianbattersby** [comment]
@david-driscoll Apologies for the delay getting back! Nothing new to report from me I'm afraid, the work to use the undo-tree for partial update diffs (opposed to the home-baked tracking it has now) unfortunately hasn't moved on since November, but I'm still keen to finish it.

**Comment by gkochanowsky** [comment]
I've banged out a SCRUD example [https://github.com/gkochanowsky/SCRUD] that represents the kind of scaffolded output I would like to produce from OmniSharp-Scaffolding. I thought this might be useful for the discussion. It is also an example of the messiness I encountered caused by the lack of @Html.Action(). This is a work in progress, any ideas are appreciated.

**Comment by david-driscoll** [comment]
We also have a Kestrel issue that may / may not block us shipping rc2, and then being able to move onto `dotnet` support.  Any input on how to work around it would be great.

https://github.com/OmniSharp/omnisharp-roslyn/pull/370#issuecomment-169793909

I dunno if @halter73 or @benaadams have any input for Wednesday, but if you're able to come, you're welcome. :smile:

**Comment by david-driscoll** [comment]
You that time while you're writing out meaningful comments, and you're brain is just working on the problem for you while you're writing... I think I figured out the cause of the problem, which might actually be an issue on the OmniSharp side instead of on the Kestrel side of things.

**Comment by david-driscoll** [comment]
@sayedihashimi is there any way to record the meeting, so we could keep it for anyone that wants to listen to it after the fact?

**Comment by sayedihashimi** [comment]
Sure we can record and upload to YouTube.

**Comment by david-driscoll** [comment]
That'd be great!

**Comment by peterblazejewicz** [comment]
I had to stay at work late with a project, dang, sorry folks! The minutes from the meeting would be great. could be via private gist/email.
Thanks!

**Comment by sayedihashimi** [comment]
Video posted at https://youtu.be/bwA-q897INk

**Comment by Yantrio** [comment]
Woops, i forgot it was tonight.

**Comment by david-driscoll** [comment]
I have a few notes that I made that I'll be posting later, just hadn't had a chance yet!

**Comment by david-driscoll** [comment]
Key points from the meeting:
- Roslyn team is focused on making sure that vscode is working well, and making fixes to Roslyn and OmniSharp-roslyn as appropriate.
-  OmniSharp-roslyn, we'll select a version of dnx-rc2 and pin specifically to that version.  This will let us finish off the rc2 branch and release that so we can move on to dotnet cli.
- We're going to look into what it will take to support dnx / dotnet cli side-by-side for a time.
  - If it's an easy win, or something that is just given too use based on the nature of how the tooling works, that will be good.
  - If it isn't an easy win we'll have to discuss what the best course of action is.
  - I'm going to see if I can get the rc2 branch released by the weekend, if anyone with a **linux / mac** machine has time to test the branch before then, that'd be a great help!
- Scaffolding is on hold until all this dotnet cli non-sense dies down, to figure out the best way to move forward.
- aspnet-generator will work on getting rc2 templates in place.

**Comment by DustinCampbell** [comment]
Thanks for writing these up @david-driscoll

**Comment by peterblazejewicz** [comment]
:ack:
Thanks!

**Comment by david-driscoll** [comment]
@peterblazejewicz, @sayedihashimi was going to let you know too. :smile:

**Comment by sayedihashimi** [comment]
Thanks David

**Comment by david-driscoll** [comment]
I don't want anyone to feel like they got thrown under the bus, that's not what the meeting is about.

**Comment by robbert229** [comment]
@david-driscoll is there going to be a February meeting?

**Comment by david-driscoll** [comment]
Yeah going to put one together for next week
